# Generated by Django 5.0.3 on 2024-03-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzbekistan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Uzbekistan')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='Uzbekistan/', verbose_name='Image')),
                ('Area', models.CharField(max_length=255, verbose_name='Area')),
            ],
        ),
    ]
