# Generated by Django 5.0.3 on 2024-03-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Uzbekistan', '0002_alter_uzbekistan_image_alter_uzbekistan_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uzbekistan',
            new_name='Region',
        ),
    ]
